import { useState } from 'react';
import type { CSSProperties } from 'react';
/*
  FfButton is the React wrapper for the Stencil web component — the only Figma-backed
  primitive that ships today. It is auto-generated by @stencil/react-output-target and
  contains zero styling logic. The shared component runtime lives in the published
  @fuggetlenfe/components package.
  Visual identity arrives exclusively through the CSS imports in main.tsx
  (contract.css + brand pack), via the same token cascade that production consumer
  apps use after installing the npm packages.
*/
import { FfButton } from '@fuggetlenfe/react-wrapper';
import './App.css';

type ThemeMode = 'light' | 'dark';

type ThemeToggleOption = {
  label: string;
  value: ThemeMode;
};

/*
  CssTokenOverrides: Intersection type that extends CSSProperties with --ff-* custom property keys.
  This allows passing token overrides as inline styles without using `as CSSProperties` type assertions.
  The --ff-button-* properties defined here override the values from contract.css and the brand pack
  for this specific component instance only.
*/
type CssTokenOverrides = CSSProperties & Record<`--ff-${string}`, string>;

const themeToggleOptions: readonly ThemeToggleOption[] = [
  { label: 'Light', value: 'light' },
  { label: 'Dark', value: 'dark' }
];

const brandTwoInlineTokenStyle: CssTokenOverrides = {
  '--ff-button-padding-inline': '8px',
  '--ff-button-padding-block': '2px',
  '--ff-button-radius': '6px'
};

const variantInlineTokenStyle: CssTokenOverrides = {
  '--ff-button-padding-inline': '0.95rem',
  '--ff-button-padding-block': '0.48rem',
  '--ff-button-radius': '4px'
};

const repositoryLinks = [
  {
    label: 'Tokens + official brand packs',
    href: 'https://github.com/bogarrenato/fuggetlenfe-tokens',
    repo: 'fuggetlenfe-tokens'
  },
  {
    label: 'Framework-independent Stencil core',
    href: 'https://github.com/bogarrenato/fuggetlenfe-components',
    repo: 'fuggetlenfe-components'
  },
  {
    label: 'React wrapper + demo',
    href: 'https://github.com/bogarrenato/fuggetlenfe-react-wrapper',
    repo: 'fuggetlenfe-react-wrapper'
  },
  {
    label: 'Angular wrapper + demo',
    href: 'https://github.com/bogarrenato/fuggetlenfe-angular-wrapper',
    repo: 'fuggetlenfe-angular-wrapper'
  }
] as const;

function App() {
  const [activeTheme, setActiveTheme] = useState<ThemeMode>('light');

  /*
    data-brand and data-theme on the shell element activate the brand pack CSS.
    The brand pack overrides --ff-button-* variables via [data-brand][data-theme] selectors.
    Every Ff* component inside this shell inherits the Brand 2 visual identity automatically.
  */
  return (
    <main className="consumer-shell" data-brand="brand-2" data-theme={activeTheme}>
      <section className="hero-card">
        <p className="eyebrow">React app · external CSS brand pack</p>
        <h1>React consumes only the wrapper logic, then receives Brand 2 from Figma-based CSS.</h1>
        <p className="body-copy">
          This app imports the compiled React wrapper plus the Brand 2 light and dark packs that
          follow the Figma token set. Brand and theme live on the outer shell, so the Stencil
          primitive stays visually neutral until the external stylesheet is present.
        </p>

        <div className="theme-bar" role="group" aria-label="Theme switcher">
          <p className="theme-label">Theme pack</p>
          <div className="theme-actions">
            {themeToggleOptions.map((themeToggleOption) => (
              <button
                key={themeToggleOption.value}
                type="button"
                className="theme-button"
                data-selected={activeTheme === themeToggleOption.value}
                onClick={() => setActiveTheme(themeToggleOption.value)}
              >
                {themeToggleOption.label}
              </button>
            ))}
          </div>
        </div>

        <div className="button-row">
          <FfButton className="brand-host">Brand 2 default</FfButton>
          <FfButton className="pill-host">Class-based override</FfButton>
          <FfButton style={brandTwoInlineTokenStyle}>Inline token tweak</FfButton>
        </div>
      </section>

      <section className="variants-section">
        <p className="eyebrow">All variants</p>
        <h2 className="section-title">Component API</h2>
        <div className="variants-grid">
          <div className="variant-item">
            <FfButton>Default</FfButton>
            <span className="variant-label">Default button</span>
          </div>
          <div className="variant-item">
            <FfButton disabled>Disabled</FfButton>
            <span className="variant-label">Disabled state</span>
          </div>
          <div className="variant-item">
            <FfButton fullWidth>Full width</FfButton>
            <span className="variant-label">Full-width layout</span>
          </div>
          <div className="variant-item">
            <FfButton type="submit">Submit</FfButton>
            <span className="variant-label">Type: submit</span>
          </div>
          <div className="variant-item">
            <FfButton type="reset">Reset</FfButton>
            <span className="variant-label">Type: reset</span>
          </div>
          <div className="variant-item">
            <FfButton className="pill-host">Pill shape</FfButton>
            <span className="variant-label">Class override (border-radius: 999px)</span>
          </div>
          <div className="variant-item">
            <FfButton style={variantInlineTokenStyle}>Custom tokens</FfButton>
            <span className="variant-label">Inline token override</span>
          </div>
          <div className="variant-item">
            <FfButton>{'\u2192 Next'}</FfButton>
            <span className="variant-label">Slotted icon text</span>
          </div>
        </div>
      </section>

      <section className="variants-section">
        <p className="eyebrow">Icon slots</p>
        <h2 className="section-title">icon-start &amp; icon-end</h2>
        <div className="variants-grid">
          <div className="variant-item">
            <FfButton>
              <svg slot="icon-start" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8l4 4 8-8" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
              Confirm
            </FfButton>
            <span className="variant-label">icon-start (check)</span>
          </div>
          <div className="variant-item">
            <FfButton>
              Download
              <svg slot="icon-end" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M8 1v10M4 8l4 4 4-4M2 14h12" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
            </FfButton>
            <span className="variant-label">icon-end (download)</span>
          </div>
          <div className="variant-item">
            <FfButton>
              <svg slot="icon-start" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M1 8l7 7 7-7M8 15V1" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" transform="rotate(180 8 8)"/></svg>
              Sync
              <svg slot="icon-end" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M1 8l7 7 7-7M8 15V1" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
            </FfButton>
            <span className="variant-label">Both slots</span>
          </div>
          <div className="variant-item">
            <FfButton ffAriaLabel="Search">
              <svg slot="icon-start" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><circle cx="6.5" cy="6.5" r="4.5" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M10 10l4 4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
            </FfButton>
            <span className="variant-label">Icon-only + aria-label</span>
          </div>
          <div className="variant-item">
            <FfButton disabled>
              <svg slot="icon-start" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8l4 4 8-8" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
              Disabled icon
            </FfButton>
            <span className="variant-label">Disabled + icon</span>
          </div>
          <div className="variant-item">
            <FfButton fullWidth>
              <svg slot="icon-start" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" aria-hidden="true"><path d="M8 1l7 7-7 7M15 8H1" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
              Full width with icon
            </FfButton>
            <span className="variant-label">Full-width + icon</span>
          </div>
        </div>
      </section>

      <section className="info-grid repo-grid">
        <article className="info-card">
          <p className="eyebrow">Repository map</p>
          <div className="detail-block" aria-label="Repository map">
            {repositoryLinks.map((repositoryLink) => (
              <a
                key={repositoryLink.repo}
                className="repo-link"
                href={repositoryLink.href}
                rel="noreferrer"
                target="_blank"
              >
                <strong>{repositoryLink.label}</strong>
                <span>{repositoryLink.repo}</span>
              </a>
            ))}
          </div>
        </article>

        <article className="info-card">
          <p className="eyebrow">Best practices proved</p>
          <div className="proof-list">
            <div className="proof-item">Semantic-first token contract lives outside the wrapper and outside the component runtime.</div>
            <div className="proof-item">The Stencil core stays logic-only and brand-neutral until external CSS is imported.</div>
            <div className="proof-item">The React wrapper only bridges props and events. It does not own theming or business rules.</div>
            <div className="proof-item">The demo imports published package names and documents the repo boundaries so the polyrepo shape stays visible.</div>
          </div>
        </article>
      </section>

      <section className="info-grid">
        <article className="info-card">
          <p className="eyebrow">Consumer imports</p>
          <div className="detail-block" aria-label="Consumer imports">
            <div className="detail-line">Import the React wrapper package.</div>
            <div className="detail-line">Import the shared token contract.</div>
            <div className="detail-line">Import the Brand 2 light stylesheet.</div>
            <div className="detail-line">Import the Brand 2 dark stylesheet.</div>
            <div className="detail-line detail-line--gap">
              Set <span>data-brand="brand-2"</span> and the active theme on the outer shell.
            </div>
            <div className="detail-line">Render the same FfButton logic inside that shell.</div>
          </div>
        </article>

        <article className="info-card">
          <p className="eyebrow">Theme behavior</p>
          <div className="detail-block" aria-label="Theme behavior">
            <div className="detail-line">Light and dark are swapped only by the shell.</div>
            <div className="detail-line">The button keeps the same logic API in both modes.</div>
            <div className="detail-line">Brand 2 colors come from the Figma-derived CSS pack.</div>
            <div className="detail-line">
              The current PoC stays intentionally narrow: only the button exists in Figma and ships.
            </div>
          </div>
        </article>

        <article className="info-card">
          <p className="eyebrow">What proves the separation</p>
          <div className="proof-list">
            <div className="proof-item">The wrapper package provides framework integration only.</div>
            <div className="proof-item">
              The primitives styling appears only after the brand CSS is imported.
            </div>
            <div className="proof-item">
              The shared components still accept custom classes and per-instance CSS properties.
            </div>
            <div className="proof-item">
              Removing a non-Figma primitive does not change the wrapper contract for the button.
            </div>
          </div>
        </article>
      </section>
    </main>
  );
}

export default App;
